"""Generates MAPPING.md: how FlightRecorder record fields map onto four
named regulatory/standards frameworks. This documents our own field-naming
choices (see SDK docstrings) against public requirements; it is NOT legal
advice and does not itself constitute compliance.
"""

from __future__ import annotations

MAPPING_MD = """\
# FlightRecorder field mapping

FlightRecorder ledger records use the following shape (see
`flightrecorder/ledger.py`):

```
seq, ts, tenant, agent_id, model, model_version, kind, payload_hash,
payload_enc, prev_hash, subject_id, dev_mode, hash, sig
```

The SDK (`flightrecorder/recorder.py`, `wrap_openai`) additionally records,
inside `payload`: `prompt_hash`, `output_hash`, `tool_calls`,
`estimated_cost_usd`, `latency_ms`, `agent_id`, `trust_level`,
`action_classification`, `outcome` — chosen to align with IETF-draft-style
"Agent Audit Trail" vocabulary (agent identity, action classification,
outcome, trust level) where such a draft exists, and otherwise with the
OpenTelemetry GenAI semantic conventions FlightRecorder already ingests via
`POST /v1/otel` (`gen_ai.request.model`, `gen_ai.prompt`, `gen_ai.completion`,
`gen_ai.tool.*`).

This document maps those fields onto four named frameworks. It is a
best-effort cross-reference for engineers assembling an evidence pack, not a
legal compliance certification.

## EU AI Act, Article 12 (record-keeping for high-risk AI systems)

Article 12 requires high-risk AI systems to enable automatic logging of
events "over the duration of the life cycle" sufficient to identify
situations of risk and facilitate post-market monitoring.

| Article 12 concept | FlightRecorder field |
|---|---|
| Event/period of operation | `ts` (per-record ISO-8601 timestamp) |
| Traceability of the system's functioning | `agent_id`, `model`, `model_version` |
| Identification of situations presenting risk | `kind` (`prompt`/`output`/`tool_call`/`tool_result`), `payload_hash` |
| Retention/integrity over the system life cycle | hash chain (`prev_hash`/`hash`) + Ed25519 `sig` + signed checkpoints |

## ISO/IEC 42001:2023 (AI management system) — relevant clauses

| Clause (informative) | FlightRecorder field |
|---|---|
| 8.1 Operational planning and control (documented evidence of operation) | full ledger export (`records.jsonl`) |
| 9.1 Monitoring, measurement, analysis, evaluation | `GET /v1/verify` (chain-integrity check), `estimated_cost_usd`, `latency_ms` |
| A.6 Data for AI systems (provenance) | `model`, `model_version`, `prompt_hash`, `output_hash` |
| A.9 (incident response inputs) | `kind=tool_result` with `outcome=error` records |

## FINRA Rule 17a-4(f) (electronic recordkeeping — non-erasable, non-rewriteable)

17a-4(f) requires records to be preserved in a "non-rewriteable,
non-erasable format" (WORM) with the ability to reproduce records
accurately and download indexes/records to another medium.

| 17a-4(f) requirement | FlightRecorder mechanism |
|---|---|
| Non-rewriteable / non-erasable | append-only JSONL, one fsync'd line per record, cross-process file lock (`ledger.py`); `hash`/`sig` make any post-hoc edit detectable |
| Duplicate copy / audit system | signed checkpoints (`checkpoint.py`) witness the chain head independently of the primary ledger file |
| Accurate reproduction / index | `GET /v1/export` produces `records.jsonl` + `chain_heads.json` + this `MAPPING.md` |
| Downloadable to another medium | export bundle (zip or JSONL+CSV) is a portable, self-contained artifact |

FlightRecorder itself does not certify WORM storage — pairing the export
with an actual WORM medium (e.g. S3 Object Lock, Azure immutable blob) is
the deployer's responsibility; FlightRecorder's contribution is
tamper-evidence and signed chain-of-custody on top of whatever storage is
used.

## SOC 2 CC7 (System Operations — monitoring, incident response)

| CC7 sub-criterion | FlightRecorder mechanism |
|---|---|
| CC7.1 detection of anomalies | `GET /v1/verify` flags hash/seq/prev_hash breaks |
| CC7.2 monitoring for security events | `kind=tool_result` outcome tracking; policy-gate verdicts (`policy.py::evaluate_and_record`) recorded as ledger events |
| CC7.3 evaluation of security events | export bundle gives an auditor a complete, independently verifiable timeline |
| CC7.4 incident response | `shred` records document crypto-shred (subject data destruction) events with a timestamp and reason hash |

---

*Generated by `flightrecorder/mapping.py`. Not legal advice.*
"""


def render_mapping_md() -> str:
    return MAPPING_MD
